//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wftwit2710
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmesaj
    {
        public int mesajid { get; set; }
        public Nullable<int> kimden { get; set; }
        public Nullable<int> kime { get; set; }
        public string metin { get; set; }
    }
}
